<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-1TO35R0" failures="1" tests="5" name="Personal loan" time="0.042" errors="0" timestamp="2021-10-07T14:28:39 IST">
  <testcase classname="Test.Intro" name="Demo" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Test.Intro.Demo(Intro.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Test.Intro2" name="ploan" time="0.001"/>
  <testcase classname="Test.Intro4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="Test.Intro4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="Test.Intro4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="Test.Intro" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
